import type { CalculatorDefinition, CalculatorGroup } from "./types"
import { CALCULATOR_CATEGORY_LABELS } from "./types"
import {
  bmiCalculator,
  bsaCalculator,
  idealBodyWeightCalculator,
  bmrCalculator,
  adjustedBodyWeightCalculator,
  estimatedCalorieRequirementCalculator,
  waistToHeightRatioCalculator,
  waistToHipRatioCalculator,
} from "./definitions/clinical"
import {
  creatinineClearanceCalculator,
  egfrCalculator,
  bunCreatinineRatioCalculator,
  egfrMdrdCalculator,
  fenaCalculator,
  feureaCalculator,
} from "./definitions/renal"
import {
  ldlCalculator,
  nonHdlCalculator,
  vldlCalculator,
  anionGapCalculator,
  correctedCalciumCalculator,
  totalHdlRatioCalculator,
  calciumPhosphateProductCalculator,
  ldlHdlRatioCalculator,
  deltaRatioCalculator,
  estimatedOsmolalityCalculator,
  hba1cEagCalculator,
} from "./definitions/chemistry"
import {
  // mcvCalculator,
  // mchCalculator,
  // mchcCalculator,
  redCellIndicesCalculator,
  absoluteCellCountCalculator,
  correctedWbcCalculator,
  hematocritEstimateCalculator,
  inrCalculator,
  correctedCountIncrementCalculator,
  estimatedBloodVolumeCalculator,
  internationalPrognosticIndexCalculator,
} from "./definitions/hematology"
import { molarityCalculator, normalityCalculator } from "./definitions/lab-solutions"
import { beerLambertCalculator } from "./definitions/spectrophotometry"
import {
  oncologyBsaDoseCalculator,
  oncologyDoseIntensityCalculator,
  oncologyRelativeDoseIntensityCalculator,
  oncologyCumulativeDoseCalculator,
  oncologyCycleTotalCalculator,
  carboplatinCalvertCalculator,
  oncologyDoseCapCalculator,
  oncologyRegimenDoseCalculator,
  oncologyHematologicModificationCalculator,
  oncologyOrganFunctionModificationCalculator,
  oncologyToxicitySafetyCalculator,
  oncologyAntiemeticRiskCalculator,
  oncologyFebrileNeutropeniaRiskCalculator,
  oncologyCycleProgressCalculator,
  oncologyCourseCompletionCalculator,
} from "./definitions/oncology"
import { cfuCalculator, dilutionFactorCalculator, concentrationAfterDilutionCalculator } from "./definitions/microbiology"
import {
  meanArterialPressureCalculator, ejectionFractionCalculator, cha2ds2VascCalculator,
  daptScoreCalculator, qtcCalculator, atherogenicIndexCalculator,
} from "./definitions/cardiovascular"
import {
  hctCiCalculator, conditioningDayCalculator, stemCellCollectionYieldCalculator,
  cd34CellDoseCalculator, neutrophilEngraftmentDayCalculator, donorChimerismCalculator,
} from "./definitions/stem-cell-transplant"
import {
  mgPerKgDoseCalculator,
  oralLiquidDoseVolumeCalculator,
  tabletCapsuleCountCalculator,
  doseVolumeRoundingCalculator,
  mgPerKgDayCalculator,
  mgPerM2DoseCalculator,
  dosePerAdministrationCalculator,
  doseVolumeCalculator,
  drugConcentrationCalculator,
  infusionRateCalculator,
  dropsPerMinuteCalculator,
  maximumDoseCheckCalculator,
  artesunateSevereMalariaCalculator,
  artemetherLumefantrineCalculator,
  artesunateAmodiaquineCalculator,
  artesunateMefloquineCalculator,
  dihydroartemisininPiperaquineCalculator,
  artesunateSulfadoxinePyrimethamineCalculator,
  artesunatePyronaridineCalculator,
  amoxicillinPediatricCalculator,
  amoxicillinClavulanatePediatricCalculator,
  azithromycinPediatricCalculator,
  ceftriaxonePediatricCalculator,
  cephalexinPediatricCalculator,
  metronidazolePediatricCalculator,
  cefuroximeSurgicalProphylaxisCalculator,
  ampicillinPediatricCalculator,
  cefotaximePediatricCalculator,
  cloxacillinPediatricCalculator,
  ciprofloxacinPediatricCalculator,
  gentamicinPediatricCalculator,
  meropenemPediatricCalculator,
  vancomycinPediatricCalculator,
  amoxicillinClavulanateRenalAdjustmentCalculator,
  ciprofloxacinRenalAdjustmentCalculator,
  cefotaximeRenalAdjustmentCalculator,
  cefuroximeAxetilRenalAdjustmentCalculator,
  meropenemRenalAdjustmentCalculator,
  vancomycinAuc24TargetCalculator,
  gentamicinPeakTroughCheckerCalculator,
  whoYoungInfantSepsisPneumoniaCalculator,
  whoYoungInfantMeningitisCalculator,
  piperacillinTazobactamPediatricCalculator,
  clindamycinPediatricCalculator,
  cefazolinPediatricCalculator,
  linezolidPediatricCalculator,
  doxycyclinePediatricCalculator,
  loadingDoseCalculator,
  maintenanceDoseCalculator,
  infusionDurationCalculator,
  courseTotalDoseCalculator,
  whoPediatricPneumoniaRegimenCalculator,
  whoPediatricDiarrhoeaZincCalculator,
  whoPediatricOrsPlanBCalculator,
  whoPediatricOrsOngoingLossCalculator,
  whoPediatricMaintenanceFluidCalculator,
  pediatricFluidDeficitCalculator,
} from "./definitions/dosing"

export const calculators: CalculatorDefinition[] = [
  bmiCalculator,
  bsaCalculator,
  idealBodyWeightCalculator,
  bmrCalculator,
  adjustedBodyWeightCalculator,
  estimatedCalorieRequirementCalculator,
  waistToHeightRatioCalculator,
  waistToHipRatioCalculator,
  creatinineClearanceCalculator,
  egfrCalculator,
  bunCreatinineRatioCalculator,
  egfrMdrdCalculator,
  fenaCalculator,
  feureaCalculator,
  ldlCalculator,
  nonHdlCalculator,
  vldlCalculator,
  anionGapCalculator,
  correctedCalciumCalculator,
  totalHdlRatioCalculator,
  calciumPhosphateProductCalculator,
  ldlHdlRatioCalculator,
  deltaRatioCalculator,
  estimatedOsmolalityCalculator,
  hba1cEagCalculator,
  // mcvCalculator,
  // mchCalculator,
  // mchcCalculator,
  redCellIndicesCalculator,
  absoluteCellCountCalculator,
  correctedWbcCalculator,
  hematocritEstimateCalculator,
  inrCalculator,
  correctedCountIncrementCalculator,
  estimatedBloodVolumeCalculator,
  internationalPrognosticIndexCalculator,
  molarityCalculator,
  normalityCalculator,
  beerLambertCalculator,
  cfuCalculator,
  dilutionFactorCalculator,
  concentrationAfterDilutionCalculator,
  mgPerKgDoseCalculator,
  oralLiquidDoseVolumeCalculator,
  tabletCapsuleCountCalculator,
  doseVolumeRoundingCalculator,
  mgPerKgDayCalculator,
  mgPerM2DoseCalculator,
  dosePerAdministrationCalculator,
  doseVolumeCalculator,
  drugConcentrationCalculator,
  infusionRateCalculator,
  dropsPerMinuteCalculator,
  maximumDoseCheckCalculator,
  artesunateSevereMalariaCalculator,
  artemetherLumefantrineCalculator,
  artesunateAmodiaquineCalculator,
  artesunateMefloquineCalculator,
  dihydroartemisininPiperaquineCalculator,
  artesunateSulfadoxinePyrimethamineCalculator,
  artesunatePyronaridineCalculator,
  amoxicillinPediatricCalculator,
  amoxicillinClavulanatePediatricCalculator,
  azithromycinPediatricCalculator,
  ceftriaxonePediatricCalculator,
  cephalexinPediatricCalculator,
  metronidazolePediatricCalculator,
  cefuroximeSurgicalProphylaxisCalculator,
  ampicillinPediatricCalculator,
  cefotaximePediatricCalculator,
  cloxacillinPediatricCalculator,
  ciprofloxacinPediatricCalculator,
  gentamicinPediatricCalculator,
  meropenemPediatricCalculator,
  vancomycinPediatricCalculator,
  amoxicillinClavulanateRenalAdjustmentCalculator,
  ciprofloxacinRenalAdjustmentCalculator,
  cefotaximeRenalAdjustmentCalculator,
  cefuroximeAxetilRenalAdjustmentCalculator,
  meropenemRenalAdjustmentCalculator,
  vancomycinAuc24TargetCalculator,
  gentamicinPeakTroughCheckerCalculator,
  whoYoungInfantSepsisPneumoniaCalculator,
  whoYoungInfantMeningitisCalculator,
  piperacillinTazobactamPediatricCalculator,
  clindamycinPediatricCalculator,
  cefazolinPediatricCalculator,
  linezolidPediatricCalculator,
  doxycyclinePediatricCalculator,
  loadingDoseCalculator,
  maintenanceDoseCalculator,
  infusionDurationCalculator,
  courseTotalDoseCalculator,
  whoPediatricPneumoniaRegimenCalculator,
  whoPediatricDiarrhoeaZincCalculator,
  whoPediatricOrsPlanBCalculator,
  whoPediatricOrsOngoingLossCalculator,
  whoPediatricMaintenanceFluidCalculator,
  pediatricFluidDeficitCalculator,
  meanArterialPressureCalculator,
  ejectionFractionCalculator,
  cha2ds2VascCalculator,
  daptScoreCalculator,
  qtcCalculator,
  atherogenicIndexCalculator,
  hctCiCalculator,
  conditioningDayCalculator,
  stemCellCollectionYieldCalculator,
  cd34CellDoseCalculator,
  neutrophilEngraftmentDayCalculator,
  donorChimerismCalculator,
  oncologyBsaDoseCalculator,
  oncologyDoseIntensityCalculator,
  oncologyRelativeDoseIntensityCalculator,
  oncologyCumulativeDoseCalculator,
  oncologyCycleTotalCalculator,
  carboplatinCalvertCalculator,
  oncologyDoseCapCalculator,
  oncologyRegimenDoseCalculator,
  oncologyHematologicModificationCalculator,
  oncologyOrganFunctionModificationCalculator,
  oncologyToxicitySafetyCalculator,
  oncologyAntiemeticRiskCalculator,
  oncologyFebrileNeutropeniaRiskCalculator,
  oncologyCycleProgressCalculator,
  oncologyCourseCompletionCalculator,
]

export function getCalculatorById(id: string): CalculatorDefinition | undefined {
  return calculators.find((c) => c.id === id)
}

export function getCalculatorsByCategory(category: CalculatorGroup): CalculatorDefinition[] {
  return calculators.filter((c) => c.category === category)
}

export function getRelatedCalculators(def: CalculatorDefinition): CalculatorDefinition[] {
  if (!def.relatedTools?.length) return []
  return def.relatedTools.map((id) => getCalculatorById(id)).filter((c): c is CalculatorDefinition => Boolean(c))
}

export const calculatorCatalog: { id: CalculatorGroup; label: string; count: number }[] = (
  Object.keys(CALCULATOR_CATEGORY_LABELS) as CalculatorGroup[]
).map((id) => ({
  id,
  label: CALCULATOR_CATEGORY_LABELS[id],
  count: getCalculatorsByCategory(id).length,
}))

export const calculatorCategories = calculatorCatalog.filter((c) => c.count > 0)

export function getCalculatorsByCategoryAndSubcategory(category: CalculatorGroup, subcategory: string): CalculatorDefinition[] {
  return getCalculatorsByCategory(category).filter((calculator) => calculator.subcategory === subcategory)
}

export function searchCalculators(query: string): CalculatorDefinition[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return calculators.filter((c) => {
    const haystack = [c.name, c.shortName ?? "", c.description, ...(c.keywords ?? [])].join(" ").toLowerCase()
    return haystack.includes(q)
  })
}

export * from "./types"
