import {
  getTreatmentRegimensBySpecialty,
  getTreatmentRegimenById,
  searchTreatmentRegimens,
  validateTreatmentRegistry,
  type TreatmentRegimen,
  type TreatmentSearchOptions,
  type TreatmentSpecialty,
} from "./treatment-engine"

const EVIQ_LAST_VERIFIED = "2026-09-15"

/**
 * Phase 27: source-backed oncology regimen references.
 *
 * These are protocol references, not patient-specific prescriptions. The
 * regimen metadata intentionally keeps the source protocol attached so a UI
 * can show the indication, population, schedule and verification status.
 */
export const treatmentRegimens: TreatmentRegimen[] = [
  {
    id: "r-chop21-dlbcl",
    name: "R-CHOP21 — Diffuse Large B-Cell Lymphoma",
    specialty: "oncology",
    disease: "Diffuse large B-cell lymphoma",
    indication: "Adult B-cell non-Hodgkin lymphoma / DLBCL reference regimen",
    population: "adult",
    ageRange: "Adult",
    cycleLength: "21 days",
    cycleCount: "6 to 8 cycles in the cited eviQ protocol",
    drugs: [
      { id: "rituximab", drug: "Rituximab", doseBasis: "mg/m2", dose: 375, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "cyclophosphamide", drug: "Cyclophosphamide", doseBasis: "mg/m2", dose: 750, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "doxorubicin", drug: "Doxorubicin", doseBasis: "mg/m2", dose: 50, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "vincristine", drug: "Vincristine", doseBasis: "mg/m2", dose: 1.4, doseUnit: "mg/m²", maximum: 2, maximumUnit: "mg", route: "IV infusion", frequency: "Day 1" },
      { id: "prednisolone", drug: "Prednisolone", doseBasis: "fixed", dose: 100, doseUnit: "mg", route: "PO", frequency: "Once daily, days 1–5" },
    ],
    prerequisites: ["Confirm histology, stage, indication and current institutional protocol before treatment."],
    monitoring: ["Protocol-defined laboratory monitoring and treatment-toxicity assessment."],
    doseModifications: [
      { id: "rchop-anc-platelets", trigger: "ANC <1.0 × 10⁹/L and/or platelets <75 × 10⁹/L", action: "Dose modification is not generally indicated in the cited protocol; consider treatment delay and/or G-CSF according to clinical judgement.", criteria: { anyOf: [{ ancLessThan: 1.0 }, { plateletsLessThan: 75 }] } },
      { id: "rchop-hepatic-bilirubin-20-50", domain: "hepatic", trigger: "Bilirubin 20–50 µmol/L", action: "Reduce doxorubicin by 50%.", appliesTo: ["doxorubicin"], criteria: { bilirubinAtLeast: 20, bilirubinLessThan: 50 } },
      { id: "rchop-hepatic-bilirubin-51-85", domain: "hepatic", trigger: "Bilirubin 51–85 µmol/L", action: "Reduce doxorubicin by 75% and vincristine by 50%.", appliesTo: ["doxorubicin", "vincristine"], criteria: { bilirubinAtLeast: 51, bilirubinLessThan: 85 } },
      { id: "rchop-hepatic-bilirubin-over-85", domain: "hepatic", trigger: "Bilirubin >85 µmol/L", action: "Do not use the protocol as written; consider an alternative protocol with specialist review.", appliesTo: ["doxorubicin", "vincristine"], criteria: { bilirubinGreaterThan: 85 } },
      { id: "rchop-neuropathy-g2", domain: "toxicity", trigger: "Peripheral neuropathy grade 2", action: "Consider omitting vincristine.", appliesTo: ["vincristine"], criteria: { toxicityType: "peripheral-neuropathy", toxicityGrade: 2 } },
    ],
    warnings: [
      "R-CHOP has multiple indication-specific variations; this entry represents the cited R-CHOP21 protocol and must not be generalized to every lymphoma.",
      "The regimen does not calculate individualized dose reductions or supportive-care prescriptions.",
    ],
    references: [
      {
        source: "eviQ — R-CHOP21 (protocol 70)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/haematology/lymphoma/other-b-cell-lymphoma/70-r-chop21-rituximab-cyclophosphamide-doxorubici",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: rituximab 375 mg/m², cyclophosphamide 750 mg/m², doxorubicin 50 mg/m², vincristine 1.4 mg/m² capped at 2 mg on day 1; prednisolone 100 mg days 1–5; every 21 days.",
      },
      {
        source: "NCI Drug Dictionary — R-CHOP",
        version: "Current page",
        url: "https://www.cancer.gov/publications/dictionaries/cancer-drug/def/r-chop-regimen",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "supporting",
        note: "Confirms the R-CHOP component combination and lymphoma uses.",
      },
    ],
    status: "current",
  },
  {
    id: "abvd-hodgkin-lymphoma",
    name: "ABVD — Hodgkin Lymphoma",
    specialty: "oncology",
    disease: "Hodgkin lymphoma",
    indication: "Hodgkin lymphoma reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "28 days",
    cycleCount: "Up to 6 cycles in the cited advanced-stage protocol",
    drugs: [
      { id: "doxorubicin", drug: "Doxorubicin", doseBasis: "mg/m2", dose: 25, doseUnit: "mg/m²", route: "IV", frequency: "Days 1 and 15" },
      { id: "bleomycin", drug: "Bleomycin", doseBasis: "units/m2", dose: 10000, doseUnit: "International Units/m²", route: "IV", frequency: "Days 1 and 15", notes: ["Dose is expressed in International Units/m² in the cited protocol."] },
      { id: "vinblastine", drug: "Vinblastine", doseBasis: "mg/m2", dose: 6, doseUnit: "mg/m²", route: "IV", frequency: "Days 1 and 15" },
      { id: "dacarbazine", drug: "Dacarbazine", doseBasis: "mg/m2", dose: 375, doseUnit: "mg/m²", route: "IV infusion", frequency: "Days 1 and 15" },
    ],
    prerequisites: ["Confirm disease setting and whether the selected protocol remains appropriate after response assessment."],
    monitoring: ["Protocol-defined laboratory monitoring and pulmonary/toxicity assessment."],
    warnings: [
      "Bleomycin units must not be silently converted to mg by mass; the cited protocol specifies International Units/m² and notes potency equivalence.",
      "The cited advanced-stage protocol contains disease- and response-dependent treatment decisions.",
    ],
    references: [
      {
        source: "eviQ — Advanced stage ABVD (protocol 56)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/haematology/lymphoma/hodgkin-lymphoma/56-advanced-stage-abvd-doxorubicin-bleomycin-vinb",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: doxorubicin 25 mg/m², vinblastine 6 mg/m², dacarbazine 375 mg/m² and bleomycin 10,000 IU/m² on days 1 and 15 every 28 days, six cycles unless progression or unacceptable toxicity.",
      },
      {
        source: "NCI — ABVD",
        version: "Updated May 10, 2023",
        url: "https://www.cancer.gov/about-cancer/treatment/drugs/abvd",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "supporting",
        note: "Confirms ABVD components and Hodgkin lymphoma use.",
      },
    ],
    status: "current",
  },
  {
    id: "mfolfox6-colorectal",
    name: "mFOLFOX6 — Colorectal Cancer",
    specialty: "oncology",
    disease: "Colorectal cancer",
    indication: "Colorectal cancer reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "14 days",
    cycleCount: "Protocol-dependent; cited metastatic protocol continues until progression or unacceptable toxicity",
    drugs: [
      { id: "oxaliplatin", drug: "Oxaliplatin", doseBasis: "mg/m2", dose: 85, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "leucovorin", drug: "Calcium folinate (Leucovorin)", doseBasis: "fixed", dose: 50, doseUnit: "mg", route: "IV bolus", frequency: "Day 1" },
      { id: "fluorouracil-bolus", drug: "Fluorouracil", doseBasis: "mg/m2", dose: 400, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "fluorouracil-infusion", drug: "Fluorouracil", doseBasis: "mg/m2", dose: 2400, doseUnit: "mg/m²", route: "Continuous IV infusion", frequency: "Over 46 hours from day 1" },
    ],
    prerequisites: ["Confirm the exact FOLFOX variant and indication; FOLFOX protocols differ in agent dosing and administration schedule."],
    monitoring: ["Protocol-defined CBC, chemistry, toxicity and fluoropyrimidine/DPD considerations."],
    doseModifications: [
      { id: "mfolfox6-anc-1-1-1-5", trigger: "ANC 1.0 to <1.5 × 10⁹/L", action: "Refer to local institutional guidelines; the cited protocol states treatment may continue if the patient is clinically well.", criteria: { ancAtLeast: 1.0, ancLessThan: 1.5 } },
      { id: "mfolfox6-anc-0-5-1-0", trigger: "ANC 0.5 to <1.0 × 10⁹/L", action: "Delay treatment until recovery.", criteria: { ancAtLeast: 0.5, ancLessThan: 1.0 } },
      { id: "mfolfox6-anc-under-0-5", trigger: "ANC <0.5 × 10⁹/L", action: "Delay treatment until recovery and consider reducing oxaliplatin and fluorouracil by 25% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { ancLessThan: 0.5 } },
      { id: "mfolfox6-febrile-neutropenia", trigger: "Febrile neutropenia", action: "Delay treatment until recovery and consider reducing oxaliplatin and fluorouracil by 25% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { febrileNeutropenia: true } },
      { id: "mfolfox6-platelets-75-100", trigger: "Platelets 75 to <100 × 10⁹/L", action: "Refer to local institutional guidelines; the cited protocol states treatment may continue if the patient is clinically well.", criteria: { plateletsAtLeast: 75, plateletsLessThan: 100 } },
      { id: "mfolfox6-mucositis-g2-occurrence-1", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, first occurrence", action: "Delay until grade 1 or less; no dose reduction.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 1 } },
      { id: "mfolfox6-mucositis-g2-occurrence-2", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, second occurrence", action: "Delay until grade 1 or less; reduce oxaliplatin and fluorouracil by 25% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 2 } },
      { id: "mfolfox6-mucositis-g2-occurrence-3", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, third occurrence", action: "Delay until grade 1 or less; reduce oxaliplatin and fluorouracil by 50% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 3 } },
      { id: "mfolfox6-mucositis-g2-occurrence-4", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, fourth occurrence", action: "Delay until grade 1 or less and withhold chemotherapy.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 4 } },
      { id: "mfolfox6-diarrhoea-g2-occurrence-1", domain: "toxicity", trigger: "Diarrhoea grade 2, first occurrence", action: "Delay until grade 1 or less; no dose reduction.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", toxicityGrade: 2, occurrence: 1 } },
      { id: "mfolfox6-diarrhoea-g2-occurrence-2", domain: "toxicity", trigger: "Diarrhoea grade 2, second occurrence", action: "Delay until grade 1 or less; reduce oxaliplatin and fluorouracil by 25% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", toxicityGrade: 2, occurrence: 2 } },
      { id: "mfolfox6-diarrhoea-g2-occurrence-3", domain: "toxicity", trigger: "Diarrhoea grade 2, third occurrence", action: "Delay until grade 1 or less; reduce oxaliplatin and fluorouracil by 50% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", toxicityGrade: 2, occurrence: 3 } },
      { id: "mfolfox6-diarrhoea-g2-occurrence-4", domain: "toxicity", trigger: "Diarrhoea grade 2, fourth occurrence", action: "Delay until grade 1 or less and withhold chemotherapy.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", toxicityGrade: 2, occurrence: 4 } },
      { id: "mfolfox6-diarrhoea-g34-occurrence-1", domain: "toxicity", trigger: "Diarrhoea grade 3 or 4, first occurrence", action: "Delay until grade 1 or less; reduce oxaliplatin and fluorouracil by 50% for subsequent cycles.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", anyOf: [{ toxicityGrade: 3 }, { toxicityGrade: 4 }], occurrence: 1 } },
      { id: "mfolfox6-diarrhoea-g34-occurrence-2", domain: "toxicity", trigger: "Diarrhoea grade 3 or 4, second occurrence", action: "Delay until grade 1 or less and withhold chemotherapy.", appliesTo: ["oxaliplatin", "fluorouracil-bolus", "fluorouracil-infusion"], criteria: { toxicityType: "diarrhoea", anyOf: [{ toxicityGrade: 3 }, { toxicityGrade: 4 }], occurrence: 2 } },
    ],
    warnings: [
      "FOLFOX is a family of regimens; this entry specifically represents the cited modified FOLFOX6 protocol.",
      "The cited eviQ protocol notes that supportive therapy and institutional details may vary.",
    ],
    references: [
      {
        source: "eviQ — Colorectal metastatic mFOLFOX6 (protocol 114)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/medical-oncology/colorectal/metastatic/114-colorectal-metastatic-folfox6-modified-fluo",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: oxaliplatin 85 mg/m², leucovorin 50 mg, 5-FU 400 mg/m² IV followed by 2,400 mg/m² continuous infusion over 46 hours, every 14 days.",
      },
      {
        source: "NCI Drug Dictionary — FOLFOX",
        version: "Updated April 27, 2023",
        url: "https://www.cancer.gov/publications/dictionaries/cancer-drug/def/folfox-regimen",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "supporting",
        note: "Confirms FOLFOX components and colorectal cancer use; NCI notes that FOLFOX variants differ in dosing and administration schedule.",
      },
    ],
    status: "current",
  },
  {
    id: "folfiri-colorectal",
    name: "FOLFIRI — Advanced/Metastatic Colorectal Cancer",
    specialty: "oncology",
    disease: "Colorectal cancer",
    indication: "Advanced or metastatic colorectal cancer reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "14 days",
    cycleCount: "Cited protocol: cycle 1 and further cycles",
    drugs: [
      { id: "irinotecan", drug: "Irinotecan", doseBasis: "mg/m2", dose: 180, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "leucovorin", drug: "Calcium folinate (Leucovorin)", doseBasis: "fixed", dose: 50, doseUnit: "mg", route: "IV bolus", frequency: "Day 1" },
      { id: "fluorouracil-bolus", drug: "Fluorouracil", doseBasis: "mg/m2", dose: 400, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "fluorouracil-infusion", drug: "Fluorouracil", doseBasis: "mg/m2", dose: 2400, doseUnit: "mg/m²", route: "Continuous IV infusion", frequency: "Over 46 hours from day 1" },
    ],
    prerequisites: ["Confirm the exact FOLFIRI protocol and indication; doses may differ in other disease settings."],
    monitoring: ["Protocol-defined CBC, chemistry, toxicity and fluoropyrimidine/DPD considerations."],
    warnings: [
      "FOLFIRI is used across multiple disease settings and protocol doses can differ; this entry is tied to the cited modified protocol.",
      "Do not infer treatment selection, cycle count or dose modifications from this reference entry.",
    ],
    references: [
      {
        source: "eviQ — Advanced or metastatic FOLFIRI (protocol 4043)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/medical-oncology/upper-gastrointestinal/gastric-and-oesophageal-metastatic/4043-advanced-or-metastatic-folfiri-modified-fl",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: irinotecan 180 mg/m², leucovorin 50 mg, 5-FU 400 mg/m² IV followed by 2,400 mg/m² continuous infusion over 46 hours; every 14 days.",
      },
      {
        source: "NCI Drug Dictionary — FOLFIRI",
        version: "Current page",
        url: "https://www.cancer.gov/publications/dictionaries/cancer-drug/def/folfiri-regimen",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "supporting",
        note: "Confirms FOLFIRI components and its use across several gastrointestinal malignancies.",
      },
    ],
    status: "current",
  },
  {
    id: "tc-breast-adjuvant",
    name: "TC — Breast Cancer Adjuvant",
    specialty: "oncology",
    disease: "Breast cancer",
    indication: "Adjuvant breast cancer protocol reference",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "4 cycles; up to 6 in selected higher-risk disease where an anthracycline is contraindicated",
    drugs: [
      { id: "docetaxel", drug: "Docetaxel", doseBasis: "mg/m2", dose: 75, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "cyclophosphamide", drug: "Cyclophosphamide", doseBasis: "mg/m2", dose: 600, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "pegfilgrastim", drug: "Pegfilgrastim", doseBasis: "fixed", dose: 6, doseUnit: "mg", route: "Subcut", frequency: "Day 2" },
    ],
    prerequisites: ["Confirm the exact adjuvant breast-cancer indication and current institutional protocol."],
    monitoring: ["Protocol-defined blood counts and toxicity assessment; assess for docetaxel-related fluid retention and neuropathy."],
    doseModifications: [
      { id: "tc-haematologic-toxicity", trigger: "Pre-treatment toxicity grade 2 or greater", action: "Review before treatment; dose reduction, delay or omission may be required according to the protocol and clinical judgement." },
    ],
    warnings: [
      "The cited eviQ protocol is an adjuvant breast-cancer regimen; do not generalize it to other breast-cancer settings without the applicable protocol.",
      "Pegfilgrastim is included as a protocol-scheduled supportive medicine, not as an independently selected prescription.",
    ],
    references: [
      {
        source: "eviQ — Breast adjuvant TC (protocol 24)",
        version: "v.10",
        url: "https://www.eviq.org.au/medical-oncology/breast/neoadjuvant-adjuvant/24-breast-adjuvant-tc-docetaxel-and-cyclophospham",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: docetaxel 75 mg/m² and cyclophosphamide 600 mg/m² day 1 every 21 days; 4 cycles, with up to 6 considered in selected higher-risk disease; pegfilgrastim 6 mg day 2.",
      },
    ],
    status: "current",
  },
  {
    id: "tac-breast-cancer",
    name: "TAC — Breast Cancer Neoadjuvant/Adjuvant",
    specialty: "oncology",
    disease: "Breast cancer",
    indication: "Neoadjuvant or adjuvant breast cancer reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "6 cycles; up to 8 for neoadjuvant treatment",
    drugs: [
      { id: "doxorubicin", drug: "Doxorubicin", doseBasis: "mg/m2", dose: 50, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "docetaxel", drug: "Docetaxel", doseBasis: "mg/m2", dose: 75, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "cyclophosphamide", drug: "Cyclophosphamide", doseBasis: "mg/m2", dose: 500, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "pegfilgrastim", drug: "Pegfilgrastim", doseBasis: "fixed", dose: 6, doseUnit: "mg", route: "Subcut", frequency: "Day 2" },
    ],
    prerequisites: ["Confirm neoadjuvant versus adjuvant setting and the current protocol before use."],
    monitoring: ["Protocol-defined CBC and toxicity monitoring, including anthracycline cardiac assessment and taxane-related toxicity."],
    doseModifications: [
      { id: "tac-neutropenia", trigger: "ANC 0.5 to <1.0 × 10⁹/L", action: "Delay treatment until recovery.", criteria: { ancAtLeast: 0.5, ancLessThan: 1.0 } },
      { id: "tac-severe-neutropenia", trigger: "ANC <0.5 × 10⁹/L or febrile neutropenia", action: "Delay treatment until recovery and consider reducing docetaxel, doxorubicin and cyclophosphamide by 25% for subsequent cycles.", appliesTo: ["docetaxel", "doxorubicin", "cyclophosphamide"], criteria: { anyOf: [{ ancLessThan: 0.5 }, { febrileNeutropenia: true }] } },
      { id: "tac-thrombocytopenia", trigger: "Platelets <50 × 10⁹/L", action: "Delay treatment until recovery and consider reducing docetaxel, doxorubicin and cyclophosphamide by 25% for subsequent cycles.", appliesTo: ["docetaxel", "doxorubicin", "cyclophosphamide"], criteria: { plateletsLessThan: 50 } },
      { id: "tac-renal-severe", domain: "renal", trigger: "eGFR <15 mL/min/1.73 m² without kidney replacement therapy", action: "Consult a multidisciplinary oncology/haematology team with nephrology and/or clinical pharmacology for dosing management.", appliesTo: ["cyclophosphamide", "docetaxel", "doxorubicin"], criteria: { renalEgfLessThan: 15 } },
      { id: "tac-hepatic-minimal", domain: "hepatic", trigger: "Minimal hepatic dysfunction", action: "Reduce docetaxel by 25%.", appliesTo: ["docetaxel"], criteria: { hepaticDysfunction: "minimal" } },
      { id: "tac-hepatic-mild", domain: "hepatic", trigger: "Mild hepatic dysfunction", action: "Reduce doxorubicin by 25% and docetaxel by 50%.", appliesTo: ["doxorubicin", "docetaxel"], criteria: { hepaticDysfunction: "mild" } },
      { id: "tac-hepatic-moderate", domain: "hepatic", trigger: "Moderate hepatic dysfunction", action: "Reduce doxorubicin by 50% and omit docetaxel.", appliesTo: ["doxorubicin", "docetaxel"], criteria: { hepaticDysfunction: "moderate" } },
      { id: "tac-hepatic-severe", domain: "hepatic", trigger: "Severe hepatic dysfunction", action: "Omit doxorubicin and docetaxel.", appliesTo: ["doxorubicin", "docetaxel"], criteria: { hepaticDysfunction: "severe" } },
    ],
    warnings: [
      "TAC contains an anthracycline; cumulative exposure and cardiac assessment are protocol-dependent.",
      "Dose modifications are stored as protocol guidance and are not automatically applied by the patient-specific calculator.",
    ],
    references: [
      {
        source: "eviQ — Breast neoadjuvant/adjuvant TAC (protocol 4114)",
        version: "v.4",
        url: "https://www.eviq.org.au/medical-oncology/breast/neoadjuvant-adjuvant/4114-breast-neoadjuvant-adjuvant-tac-docetaxel-do",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: doxorubicin 50 mg/m², docetaxel 75 mg/m² and cyclophosphamide 500 mg/m² day 1 every 21 days; 6 cycles, up to 8 for neoadjuvant treatment; pegfilgrastim 6 mg day 2.",
      },
    ],
    status: "current",
  },
  {
    id: "tchp-breast-neoadjuvant",
    name: "TCHP — HER2-Positive Breast Cancer",
    specialty: "oncology",
    disease: "HER2-positive breast cancer",
    indication: "Neoadjuvant treatment of operable HER2-positive early breast cancer",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "6 cycles prior to surgery",
    drugs: [
      { id: "pertuzumab-loading", drug: "Pertuzumab", doseBasis: "fixed", dose: 840, doseUnit: "mg", route: "IV infusion", frequency: "Day 1, cycle 1 loading dose" },
      { id: "pertuzumab-maintenance", drug: "Pertuzumab", doseBasis: "fixed", dose: 420, doseUnit: "mg", route: "IV infusion", frequency: "Day 1, cycles 2–6" },
      { id: "trastuzumab-loading", drug: "Trastuzumab", doseBasis: "mg/kg", dose: 8, doseUnit: "mg/kg", route: "IV infusion", frequency: "Day 1, cycle 1 loading dose" },
      { id: "trastuzumab-maintenance", drug: "Trastuzumab", doseBasis: "mg/kg", dose: 6, doseUnit: "mg/kg", route: "IV infusion", frequency: "Day 1, cycles 2–6" },
      { id: "docetaxel", drug: "Docetaxel", doseBasis: "mg/m2", dose: 75, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "carboplatin", drug: "Carboplatin", doseBasis: "AUC", dose: 6, doseUnit: "AUC", route: "IV infusion", frequency: "Day 1" },
      { id: "pegfilgrastim", drug: "Pegfilgrastim", doseBasis: "fixed", dose: 6, doseUnit: "mg", route: "Subcut", frequency: "Day 2" },
    ],
    prerequisites: ["Confirm HER2-positive operable early breast cancer and protocol eligibility; confirm renal-function method for carboplatin."],
    monitoring: ["CBC, renal and liver tests before each cycle; baseline and periodic cardiac function assessment for HER2-directed therapy."],
    doseModifications: [
      { id: "tchp-severe-neutropenia", trigger: "ANC <0.5 × 10⁹/L or febrile neutropenia", action: "Delay treatment until recovery and consider reducing docetaxel and carboplatin by 25% for subsequent cycles.", appliesTo: ["docetaxel", "carboplatin"], criteria: { anyOf: [{ ancLessThan: 0.5 }, { febrileNeutropenia: true }] } },
      { id: "tchp-thrombocytopenia", trigger: "Platelets <50 × 10⁹/L", action: "Delay treatment until recovery and consider reducing docetaxel and carboplatin by 25% for subsequent cycles.", appliesTo: ["docetaxel", "carboplatin"], criteria: { plateletsLessThan: 50 } },
      { id: "tchp-neuropathy-g2-persistent", domain: "toxicity", trigger: "Grade 2 peripheral neuropathy present at the start of the next cycle", action: "Reduce docetaxel by 25%; if persistent, reduce docetaxel by 50%.", appliesTo: ["docetaxel"], criteria: { toxicityType: "peripheral-neuropathy", toxicityGrade: 2, persistentAtNextCycle: true } },
      { id: "tchp-neuropathy-g3", domain: "toxicity", trigger: "Grade 3 peripheral neuropathy", action: "Omit docetaxel.", appliesTo: ["docetaxel"], criteria: { toxicityType: "peripheral-neuropathy", toxicityGrade: 3 } },
      { id: "tchp-neuropathy-g4", domain: "toxicity", trigger: "Grade 4 peripheral neuropathy", action: "Omit docetaxel.", appliesTo: ["docetaxel"], criteria: { toxicityType: "peripheral-neuropathy", toxicityGrade: 4 } },
      { id: "tchp-mucositis-g2-occurrence-1", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, first occurrence", action: "Delay until grade 1 or less; no dose reduction.", appliesTo: ["docetaxel"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 1 } },
      { id: "tchp-mucositis-g2-occurrence-2", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, second occurrence", action: "Delay until grade 1 or less; reduce docetaxel by 25%.", appliesTo: ["docetaxel"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 2 } },
      { id: "tchp-mucositis-g2-occurrence-3", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, third occurrence", action: "Delay until grade 1 or less; reduce docetaxel by 50%.", appliesTo: ["docetaxel"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 3 } },
      { id: "tchp-mucositis-g2-occurrence-4", domain: "toxicity", trigger: "Mucositis/stomatitis grade 2, fourth occurrence", action: "Delay until grade 1 or less; omit docetaxel.", appliesTo: ["docetaxel"], criteria: { toxicityType: "mucositis-stomatitis", toxicityGrade: 2, occurrence: 4 } },
      { id: "tchp-renal-15-29", domain: "renal", trigger: "eGFR 15–29 mL/min/1.73 m²", action: "Use the target carboplatin AUC with the Calvert formula or consider an alternative protocol; docetaxel, pertuzumab and trastuzumab are listed as full dose in the cited table.", appliesTo: ["carboplatin", "docetaxel", "pertuzumab-loading", "pertuzumab-maintenance", "trastuzumab-loading", "trastuzumab-maintenance"], criteria: { renalEgfAtLeast: 15, renalEgfLessThan: 30 } },
      { id: "tchp-renal-30-44", domain: "renal", trigger: "eGFR 30–44 mL/min/1.73 m²", action: "Use the target carboplatin AUC with the Calvert formula; the cited protocol notes increased risk of adverse events; other listed agents remain full dose.", appliesTo: ["carboplatin"], criteria: { renalEgfAtLeast: 30, renalEgfLessThan: 45 } },
      { id: "tchp-renal-45-59", domain: "renal", trigger: "eGFR 45–59 mL/min/1.73 m²", action: "Use the target carboplatin AUC with the Calvert formula; the cited protocol notes increased risk of adverse events.", appliesTo: ["carboplatin"], criteria: { renalEgfAtLeast: 45, renalEgfLessThan: 60 } },
      { id: "tchp-renal-under-15", domain: "renal", trigger: "eGFR <15 mL/min/1.73 m² without kidney replacement therapy", action: "Consult a multidisciplinary oncology/haematology team with nephrology and/or clinical pharmacology for dosing management.", appliesTo: ["carboplatin"], criteria: { renalEgfLessThan: 15 } },
      { id: "tchp-hepatic-minimal", domain: "hepatic", trigger: "Minimal hepatic dysfunction", action: "Reduce docetaxel by 25%.", appliesTo: ["docetaxel"], criteria: { hepaticDysfunction: "minimal" } },
      { id: "tchp-hepatic-mild", domain: "hepatic", trigger: "Mild hepatic dysfunction", action: "Reduce docetaxel by 50%.", appliesTo: ["docetaxel"], criteria: { hepaticDysfunction: "mild" } },
      { id: "tchp-hepatic-moderate", domain: "hepatic", trigger: "Moderate hepatic dysfunction", action: "Omit docetaxel.", appliesTo: ["docetaxel"], criteria: { hepaticDysfunction: "moderate" } },
      { id: "tchp-hepatic-severe", domain: "hepatic", trigger: "Severe hepatic dysfunction", action: "Omit docetaxel.", appliesTo: ["docetaxel"], criteria: { hepaticDysfunction: "severe" } },
    ],
    warnings: [
      "Trastuzumab must not be substituted with trastuzumab emtansine or trastuzumab deruxtecan in this protocol.",
      "Carboplatin is AUC-based and therefore is intentionally not calculated by the BSA-only engine; use the dedicated Calvert calculator with the protocol-required renal-function method.",
      "Loading and subsequent doses are distinct protocol states and must not be interchanged.",
    ],
    references: [
      {
        source: "eviQ — Breast neoadjuvant TCHP (protocol 3736)",
        version: "v.4",
        url: "https://www.eviq.org.au/medical-oncology/breast/neoadjuvant-adjuvant/3736-breast-neoadjuvant-tchp-docetaxel-carboplati",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: pertuzumab 840 mg loading then 420 mg, trastuzumab 8 mg/kg loading then 6 mg/kg, docetaxel 75 mg/m², carboplatin AUC 6, every 21 days for 6 cycles; pegfilgrastim 6 mg day 2.",
      },
    ],
    status: "current",
  },
  {
    id: "sclc-atezolizumab-carboplatin-etoposide",
    name: "Atezolizumab + Carboplatin + Etoposide — Extensive-Stage SCLC",
    specialty: "oncology",
    disease: "Extensive-stage small-cell lung cancer",
    indication: "First-line extensive-stage small-cell lung cancer reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "4 combination cycles followed by atezolizumab maintenance until progression or unacceptable toxicity",
    drugs: [
      { id: "atezolizumab", drug: "Atezolizumab", doseBasis: "fixed", dose: 1200, doseUnit: "mg", route: "IV infusion", frequency: "Day 1, cycles 1–4 and maintenance" },
      { id: "carboplatin", drug: "Carboplatin", doseBasis: "AUC", dose: 5, doseUnit: "AUC", route: "IV infusion", frequency: "Day 1, cycles 1–4" },
      { id: "etoposide", drug: "Etoposide", doseBasis: "mg/m2", dose: 100, doseUnit: "mg/m²", route: "IV infusion", frequency: "Days 1–3, cycles 1–4" },
    ],
    prerequisites: ["Specialist oncology supervision and confirmation of extensive-stage SCLC and immunotherapy eligibility."],
    monitoring: ["Protocol-defined CBC, renal/hepatic monitoring and immune-related adverse-event surveillance."],
    doseModifications: [
      { id: "sclc-severe-neutropenia", trigger: "ANC <0.5 × 10⁹/L or febrile neutropenia", action: "Delay treatment and reduce carboplatin and etoposide by 25% for subsequent cycles.", appliesTo: ["carboplatin", "etoposide"], criteria: { anyOf: [{ ancLessThan: 0.5 }, { febrileNeutropenia: true }] } },
      { id: "sclc-thrombocytopenia", trigger: "Platelets <50 × 10⁹/L", action: "Delay treatment and reduce carboplatin and etoposide by 25% for subsequent cycles.", appliesTo: ["carboplatin", "etoposide"], criteria: { plateletsLessThan: 50 } },
      { id: "sclc-checkpoint-inhibitor", trigger: "Immune-related adverse event", action: "Follow the applicable immune-related adverse-event management protocol; dose reduction of atezolizumab is not recommended in the cited protocol." },
      { id: "sclc-renal-30-44", domain: "renal", trigger: "eGFR 30–44 mL/min/1.73 m²", action: "Consider a 25% reduction of etoposide and recalculate carboplatin using the Calvert formula.", appliesTo: ["etoposide", "carboplatin"], criteria: { renalEgfAtLeast: 30, renalEgfLessThan: 45 } },
      { id: "sclc-renal-15-29", domain: "renal", trigger: "eGFR 15–29 mL/min/1.73 m²", action: "Reduce etoposide by 25% and recalculate carboplatin using the Calvert formula; consider increased risk of adverse events.", appliesTo: ["etoposide", "carboplatin"], criteria: { renalEgfAtLeast: 15, renalEgfLessThan: 30 } },
      { id: "sclc-renal-under-15", domain: "renal", trigger: "eGFR <15 mL/min/1.73 m² without kidney replacement therapy", action: "Consult a multidisciplinary oncology/haematology team with nephrology and/or clinical pharmacology for dosing management.", appliesTo: ["etoposide", "carboplatin"], criteria: { renalEgfLessThan: 15 } },
      { id: "sclc-hepatic-mild", domain: "hepatic", trigger: "Mild hepatic impairment", action: "Reduce etoposide by 25%.", appliesTo: ["etoposide"], criteria: { hepaticDysfunction: "mild" } },
      { id: "sclc-hepatic-moderate", domain: "hepatic", trigger: "Moderate hepatic impairment", action: "Reduce etoposide by 50%.", appliesTo: ["etoposide"], criteria: { hepaticDysfunction: "moderate" } },
      { id: "sclc-hepatic-severe", domain: "hepatic", trigger: "Severe hepatic impairment", action: "Omit etoposide.", appliesTo: ["etoposide"], criteria: { hepaticDysfunction: "severe" } },
    ],
    warnings: [
      "This regimen includes an immune checkpoint inhibitor and requires specialist supervision and immune-related adverse-event management.",
      "Carboplatin AUC dosing is not calculated by the BSA-only engine; use the dedicated Calvert calculator with the protocol-required renal-function method.",
    ],
    references: [
      {
        source: "eviQ — SCLC extensive disease carboplatin, etoposide and atezolizumab (protocol 3731)",
        version: "v.6",
        url: "https://www.eviq.org.au/medical-oncology/respiratory/small-cell-lung-cancer/3731-sclc-extensive-disease-carboplatin-etoposide",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: atezolizumab 1,200 mg day 1, carboplatin AUC 5 day 1 and etoposide 100 mg/m² days 1–3 for four 21-day cycles, then atezolizumab maintenance.",
      },
    ],
    status: "current",
  },
  {
    id: "r-cvp-non-hodgkin-lymphoma",
    name: "R-CVP — Non-Hodgkin Lymphoma",
    specialty: "oncology",
    disease: "B-cell non-Hodgkin lymphoma",
    indication: "Non-Hodgkin lymphoma reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "6 to 8 cycles",
    drugs: [
      { id: "prednisolone", drug: "Prednisolone", doseBasis: "mg/m2", dose: 40, doseUnit: "mg/m²", route: "PO", frequency: "Once daily, days 1–5" },
      { id: "rituximab", drug: "Rituximab", doseBasis: "mg/m2", dose: 375, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "vincristine", drug: "Vincristine", doseBasis: "mg/m2", dose: 1.4, doseUnit: "mg/m²", maximum: 2, maximumUnit: "mg", route: "IV infusion", frequency: "Day 1" },
      { id: "cyclophosphamide", drug: "Cyclophosphamide", doseBasis: "mg/m2", dose: 750, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
    ],
    prerequisites: ["Confirm lymphoma subtype and treatment intent against the current protocol."],
    monitoring: ["Protocol-defined blood counts and treatment-toxicity assessment."],
    doseModifications: [
      { id: "rcvp-anc-toxicity", trigger: "ANC <1.0 × 10⁹/L", action: "Delay treatment until recovery; consider G-CSF according to local practice.", criteria: { ancLessThan: 1.0 } },
      { id: "rcvp-platelet-toxicity", trigger: "Platelets <75 × 10⁹/L", action: "Delay treatment until recovery; consider G-CSF according to local practice.", criteria: { plateletsLessThan: 75 } },
      { id: "rcvp-neuropathy", domain: "toxicity", trigger: "Peripheral neuropathy", action: "Assess before each treatment; temporary omission, dose reduction or cessation of vincristine may be indicated based on clinical findings.", appliesTo: ["vincristine"], criteria: { toxicityType: "peripheral-neuropathy", toxicityGradeAtLeast: 1 } },
      { id: "rcvp-hepatic-vincristine-50", domain: "hepatic", trigger: "Bilirubin 26–51 µmol/L OR AST/ALT 60–180 U/L", action: "Reduce vincristine by 50%.", appliesTo: ["vincristine"], criteria: { anyOf: [{ allOf: [{ bilirubinAtLeast: 26 }, { bilirubinLessThan: 52 }] }, { allOf: [{ astAltAtLeast: 60 }, { astAltLessThanOrEqual: 180 }] }] } },
      { id: "rcvp-hepatic-vincristine-50-high-bilirubin", domain: "hepatic", trigger: "Bilirubin >51 µmol/L with AST/ALT ≤180 U/L", action: "Reduce vincristine by 50%.", appliesTo: ["vincristine"], criteria: { allOf: [{ bilirubinGreaterThan: 51 }, { astAltLessThanOrEqual: 180 }] } },
      { id: "rcvp-hepatic-vincristine-omit", domain: "hepatic", trigger: "Bilirubin >51 µmol/L AND AST/ALT >180 U/L", action: "Omit vincristine.", appliesTo: ["vincristine"], criteria: { allOf: [{ bilirubinGreaterThan: 51 }, { astAltGreaterThan: 180 }] } },
    ],
    warnings: [
      "R-CVP is indication-specific; this registry entry must not be generalized to every B-cell lymphoma.",
      "Vincristine is explicitly capped at 2 mg in the cited protocol.",
    ],
    references: [
      {
        source: "eviQ — R-CVP (protocol 168)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/haematology/lymphoma/other-b-cell-lymphoma/168-r-cvp-rituximab-cyclophosphamide-vincristine",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: prednisolone 40 mg/m² days 1–5, rituximab 375 mg/m² day 1, vincristine 1.4 mg/m² capped at 2 mg, cyclophosphamide 750 mg/m² day 1 every 21 days; 6–8 cycles.",
      },
    ],
    status: "current",
  },
  {
    id: "docetaxel-prostate-metastatic",
    name: "Docetaxel + Prednisolone — Metastatic Prostate Cancer",
    specialty: "oncology",
    disease: "Metastatic prostate cancer",
    indication: "Androgen-independent (castration-resistant) metastatic prostate cancer reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "Continuous until progression or unacceptable toxicity; up to 10 cycles in cited protocol",
    drugs: [
      { id: "docetaxel", drug: "Docetaxel", doseBasis: "mg/m2", dose: 75, doseUnit: "mg/m²", route: "IV infusion", frequency: "Day 1" },
      { id: "prednisolone", drug: "Prednisolone", doseBasis: "fixed", dose: 10, doseUnit: "mg", route: "PO", frequency: "Once daily, days 1–21" },
    ],
    prerequisites: ["Confirm metastatic castration-resistant disease and current protocol; confirm ongoing androgen-deprivation therapy where applicable."],
    monitoring: ["Protocol-defined blood counts, treatment toxicity and clinical response."],
    doseModifications: [
      { id: "docetaxel-prostate-elderly-asian", trigger: "Elderly or Asian patient", action: "The cited protocol advises considering an initial docetaxel reduction to 60 mg/m² or an alternative two-weekly protocol, according to reference committee consensus." },
    ],
    warnings: [
      "Prednisolone use differs by clinical setting; the cited protocol notes it was not required in castration-sensitive patients.",
      "The cited protocol includes specific docetaxel premedication requirements and high-risk hypersensitivity considerations.",
    ],
    references: [
      {
        source: "eviQ — Prostate metastatic docetaxel three weekly and prednisolone (protocol 249)",
        version: "Current protocol page",
        url: "https://www.eviq.org.au/medical-oncology/urogenital/prostate/249-prostate-metastatic-docetaxel-three-weekly-and",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Cited schedule: docetaxel 75 mg/m² day 1 and prednisolone 10 mg once daily days 1–21 every 21 days; continuous until progression/unacceptable toxicity, up to 10 cycles.",
      },
    ],
    status: "current",
  },
  {
    id: "ac-breast-cancer",
    name: "AC — Breast Cancer",
    specialty: "oncology",
    disease: "Breast cancer",
    indication: "Doxorubicin/cyclophosphamide reference regimen",
    population: "adult",
    ageRange: "Adult protocol reference",
    cycleLength: "21 days",
    cycleCount: "Protocol-dependent",
    drugs: [
      { id: "doxorubicin", drug: "Doxorubicin", doseBasis: "mg/m2", dose: 60, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
      { id: "cyclophosphamide", drug: "Cyclophosphamide", doseBasis: "mg/m2", dose: 600, doseUnit: "mg/m²", route: "IV", frequency: "Day 1" },
    ],
    prerequisites: ["Confirm the specific breast-cancer treatment setting and current institutional protocol."],
    monitoring: ["Protocol-defined cardiac, hematologic and treatment-toxicity assessment."],
    warnings: [
      "AC is used in more than one breast-cancer treatment setting; this entry is a regimen reference and does not select treatment based on stage or tumor biology.",
      "Anthracycline exposure requires attention to prior cumulative exposure and protocol-specific cardiac assessment.",
    ],
    references: [
      {
        source: "NCI Drug Dictionary — AC regimen",
        version: "Current page",
        url: "https://www.cancer.gov/publications/dictionaries/cancer-drug/def/ac-regimen",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "current",
        note: "Confirms doxorubicin plus cyclophosphamide and breast-cancer use; NCI identifies an every-21-day regimen.",
      },
      {
        source: "NCI Breast Cancer Treatment PDQ",
        version: "Current PDQ page",
        url: "https://www.cancer.gov/types/breast/hp/breast-treatment-pdq",
        lastVerified: EVIQ_LAST_VERIFIED,
        status: "supporting",
        note: "Discusses AC as a breast-cancer chemotherapy regimen and describes its use in treatment sequences.",
      },
    ],
    status: "reference-only",
    notes: ["Dose values should be populated from the exact selected institutional/protocol version before patient-specific calculation."]
  },
]

export function getTreatmentRegimen(id: string): TreatmentRegimen | undefined {
  return getTreatmentRegimenById(treatmentRegimens, id)
}

export function getTreatmentRegimens(specialty: TreatmentSpecialty): TreatmentRegimen[] {
  return getTreatmentRegimensBySpecialty(treatmentRegimens, specialty)
}

export function searchTreatments(query: string, options?: TreatmentSearchOptions): TreatmentRegimen[] {
  return searchTreatmentRegimens(treatmentRegimens, query, options)
}

export const treatmentRegistryErrors = validateTreatmentRegistry(treatmentRegimens)
